### ISSUE TITLE
integrate armor values in the config folder

### ISSUE THREAD

**Issue by Fropaille** [Nic4Las/Minecraft-Enderite-Mod#103]
Hello, I'm developping a modpack in 1.20.1 with your mod but I would like to change the values of the tools and the armor set to make it more end game, which is possible for the tools but not for the armor. It would be immensely helpful if you could address this issue, allowing users like myself to fully customize these settings. Your assistance in this matter would be greatly appreciated. Thank you in advance for considering my request, and I look forward to your response.

**Comment by Pitti11** [comment]
Great idea, added in v1.5.1 for 1.20.2+.
Is there a specific reason for 1.20.1? And which modloader, Fabric or Forge?

**Comment by Fropaille** [comment]
1.20.1 for 2 main reasons. Firstly, its the 1.20 version with the largest number of uploaded mods. Secondly, there are sinytra connector and Forgified Fabric API wich allows you to use both forge's and fabric's mods using only forge. And so to answer your second question, it was on the Forge modloader. (btw these 2 essential mods are exclusively compatible with minecraft 1.20.1)

**Comment by Pitti11** [comment]
Alright, fixed for 1.20.1 with [359a133](https://github.com/Nic4Las/Minecraft-Enderite-Mod/commit/359a13319cbaccd3933611da062b7753db1cdafc)
