### ISSUE TITLE
(suggestion) Enderite smithing templates

### ISSUE THREAD

**Issue by baeZipster** [Nic4Las/Minecraft-Enderite-Mod#106]
they are way too common when you have mods that add more end chests like moog's end structures.
also they seem to have a really complicated way to inject them into the end city treasure loot table. i cant seem to find the loot tables for them. do you not use loot modifiers? why not? using loot modifiers allows one to make datapacks to adjust stuff like this.

**Comment by Pitti11** [comment]
Sorry for the late manual response, but we try not to use features that are only available in either NeoForge or Fabric. We build for both and the Architectury loot event allows us to setup both at the same time.
