### ISSUE TITLE
Fabric/1.16.2/1.2.0.jar FileNotFoundException

### ISSUE THREAD

**Issue by Katorone** [Nic4Las/Minecraft-Enderite-Mod#11]
On a fresh install of the mod, I'm getting this error:
`[STDERR]: java.io.FileNotFoundException: ./config/enderitemod.json`

Afterwards, no config file is created either.

Edit: Apparently the config folder isn't created automatically by fabric.  You also have to check if this folder exists, and check for the config file itself.
On my test, the config folder did exist already.

**Comment by Pitti11** [comment]
Oh, yeah, I think it should be fixed in the next release. kyrptonaught made a pull request which should fix it.

**Comment by Katorone** [comment]
Confirmed it's fixed.  Thanks!
