### ISSUE TITLE
Upgrade to 1.20.6 please

### ISSUE THREAD

**Issue by drkhodakarami** [Nic4Las/Minecraft-Enderite-Mod#113]
There are some networks and itemstack changes in 1.20.6, specially, the usage of CODEC, and Packet Codecs and networking. Reading the blog post about 1.21 changes, it looks like there are little changes regarding the mod (mainly the change of the Identifier that can be done using a single search/replace). However, it looks like the changes on 1.20.5 and 1.20.6 are much needed adjustments in the long run.

Please update the mod to the 1.20.6 version. This is a very good learning material when it comes to modding at the same time, a very good mod to play with.

**Comment by Pitti11** [comment]
Finally done with commit 9ca557f
