### ISSUE TITLE
There isn't a needs_enderite_tools tag. Enderite has the same mining level as netherite (forge 1.20.1)

### ISSUE THREAD

**Issue by BurningSulphur** [Nic4Las/Minecraft-Enderite-Mod#116]
Would be handy for modpack makers if there was a needs_enderite_tools tag so that we could make blocks require enderite to break. 

For example I would like to make gobber require enderite instead of netherite to mine.

**Comment by Pitti11** [comment]
That should be achievable by:
- inputting the block into data/minecraft/tags/incorrect_for_netherite_tool.json
(maybe also the other materials if needed)

**Comment by Pitti11** [comment]
I added a tag for the newer version, it is appended in all the vanilla "incorrect_for_<material>_tool" tags. If you would add "minecraft:stone", only enderite could mine it.
