### ISSUE TITLE
No ore, 1.20.1

### ISSUE THREAD

**Issue by CSN2856** [Nic4Las/Minecraft-Enderite-Mod#119]
Can't generate 'ore' using the latest version in 1.20.1 (forge)(No terminal mod installed) Is' ore 'not generated on the surface?

**Comment by nul666lun** [comment]
wow a month and nobody cares to reply...R.I.P.

**Comment by Nic4Las** [comment]
We checked that the ore generates befor we published the mod. No the ore does not spawn on the surface and it is rare. It does not spawn exposed to air.

**Comment by allanonmage** [comment]
The only time I saw it generate in my 1.19.2 modpack was exposed to air.

I've been playtesting my 1.20.1 fabric modpack and have not seen any, so I figured your mod didn't play well with some other mods and was going to make a translation recipe from Better End's Enderite to yours with either a datapack or a KubeJS recipe.
