### ISSUE TITLE
mod asking for cloth config while its installed

### ISSUE THREAD

**Issue by VaporeonScripts** [Nic4Las/Minecraft-Enderite-Mod#125]
neoforge 1.21.1 .74

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/6437ad12-f6cf-4872-a0da-1a6ab266dd8e)
![image](https://github.com/user-attachments/assets/2ce7d3f4-d4e3-4a0d-8075-7c2249e67bc0)

**Comment by VaporeonScripts** [comment]
https://mclo.gs/ziDBYPS

**Comment by Pitti11** [comment]
Thank you for reporting, it was a simple - instead of _ 
Hotfix is already downloadable, GitHub will follow.

**Comment by VaporeonScripts** [comment]
ty, will add the mod right now!
