### ISSUE TITLE
Feature is not a JSON object

### ISSUE THREAD

**Issue by ianmeinert** [Nic4Las/Minecraft-Enderite-Mod#13]
MC version: 1.16.2
Minecraft-Enderite-Mod version: 1.2.2-1.16.2

> Log entry: [17:40:32] [Netty Client IO #8/ERROR]: Feature: Not a JSON object: "minecraft:enderite_ore_feature";

**Comment by Pitti11** [comment]
Yeah, in the moment there is no official way of doing biomes, techreborn and our mod use mixins to fix a problem with registering features. Does the problem only happen if both are active or also if they are seperat?

**Comment by ianmeinert** [comment]
It occurred if both were separate, too.  We blasted away the server and brought installed one mod at a time and tied to one of the Oasis mods. We removed those and so far, so good.
