### ISSUE TITLE
Floating Items

### ISSUE THREAD

**Issue by haz8989** [Nic4Las/Minecraft-Enderite-Mod#22]
When i drop an enderite item it doesn't seem to be effected by gravity at all.

Demonstration: https://youtu.be/gxqQdRN-Vkk

I tested dropping items from other mods and they were normal.

**Comment by EternalShadow17** [comment]
tbh i really like this lol it makes sense, im having the issue to but id like to keep it that way haha

**Comment by haz8989** [comment]
To be honest yeah, it's actually kinda cool.
Stops you from accidently losing your items in the void!

**Comment by Pitti11** [comment]
![grafik](https://user-images.githubusercontent.com/43349907/104389544-ffebb180-553b-11eb-869b-a8fd9d463cb8.png)
It is indeed a fully intentional ability of Enderite items.^^
