### ISSUE TITLE
Crafting items crashes the game on a server

### ISSUE THREAD

**Issue by mingusman** [Nic4Las/Minecraft-Enderite-Mod#23]
the game crashes and gives this error:

The game crashed whilst container click
Error: java.lang.NullPointerException: Container click
Exit Code: -1

this happens with nearly every item that can be crafted, including furnaces, iron pickaxes, haybales to wheat, and more.

**Comment by mrCupcakewithicecream** [comment]
Me too

Can it be fixed;I love this mod so I really want it!!!

**Comment by Nic4Las** [comment]
Thanks for the report. We are aware of the issue and are working on it. Should be fixed by the next update.

**Comment by Nic4Las** [comment]
Fixed
