### ISSUE TITLE
Game crashes when launched with the rats mod installed.

### ISSUE THREAD

**Issue by Scapulaunit12** [Nic4Las/Minecraft-Enderite-Mod#24]
Whenever I launch the game with the latest version of both Enderite and Rats the game crashes with this message
![image](https://user-images.githubusercontent.com/56084328/106325600-1044a180-6249-11eb-89cf-90b3b9a8a3fd.png)

**Comment by AdnanuReeves** [comment]
I have this issue aswell. It also crashes with spartan weaponry

**Comment by CPSRYAN** [comment]
Also having the same issue, [here's the latest.log for myself](https://pastebin.ubuntu.com/p/Y2c3TW2Jf5/)
Also made a [reddit post in case a solution comes up there](https://www.reddit.com/r/FeedTheBeastCrashes/comments/ll2083/registry_object_not_present_conflict_with/)

**Comment by Edison12300** [comment]
Same issue here. In the crash report, it says Exception message: java.lang.NullPointerException: Registry Object not present: enderitemod:enderite_bow. Is there a solution now?

**Comment by Pitti11** [comment]
Fixed this issue in 1.16.4/ 1.16.5 version.
Rats and spartan weaponry will now load with our mod installed.
