### ISSUE TITLE
Cracked Enderite not dropping in multiplayer, but is dropping in singleplayer

### ISSUE THREAD

**Issue by RocketSauce28** [Nic4Las/Minecraft-Enderite-Mod#25]
Basically the title. Works in singleplayer, but the cracked enderite drops nothing in multiplayer (1.16.4)

**Comment by Nic4Las** [comment]
What version are you using Fabric or Forge?

**Comment by Pitti11** [comment]
Should be fixed with the new 1.16.4/1.16.5 versions.
