### ISSUE TITLE
Conflict with Rats mod "Registry Object not present"

### ISSUE THREAD

**Issue by CPSRYAN** [Nic4Las/Minecraft-Enderite-Mod#26]
"java.lang.NullPointerException: Registry Object not present: enderitemod:enderite_bow"
This error pops up in the log when loading Enderite alongside the Rats mod
Making my own report to try and draw attention to this, since it seems to be the same as #24 
[Leaving a reddit link in case a possible solution is found](https://www.reddit.com/r/FeedTheBeastCrashes/comments/ll2083/registry_object_not_present_conflict_with/)
[Here's the log](https://pastebin.ubuntu.com/p/Y2c3TW2Jf5/)

**Comment by Pitti11** [comment]
Fixed in 1.16.5. Tested the 1.16.4/1.16.5 version with rats and it loaded.
