### ISSUE TITLE
Mod failing to load

### ISSUE THREAD

**Issue by hayden7606** [Nic4Las/Minecraft-Enderite-Mod#28]
I get an error saying this mod failed to load and only this one. here is one of my crash files
[crash-2021-02-24_13.52.39-fml.txt](https://github.com/Nic4Las/Minecraft-Enderite-Mod/files/6038738/crash-2021-02-24_13.52.39-fml.txt)

**Comment by HidroGaming** [comment]
I think you downloaded enderite for minecraft 1.16.3 and launching forge for minecraft 1.16.4.
This is maybe the issue.

**Comment by Nic4Las** [comment]
> I think you downloaded enderite for minecraft 1.16.3 and launching forge for minecraft 1.16.4. This is maybe the issue.

Yup you got it this is a version mismatch.
