### ISSUE TITLE
Enchantment name "Void floating" should be "Void Floating"

### ISSUE THREAD

**Issue by James103** [Nic4Las/Minecraft-Enderite-Mod#30]
https://github.com/Nic4Las/Minecraft-Enderite-Mod/blob/f53749cecc8756ecad81c6b057d487318e7fe0ee/src/main/resources/assets/enderitemod/lang/en_us.json#L27

Minecraft generally uses Title Case for enchantments, such as "Luck of the Sea", "Unbreaking", "Bane of Arthropods", and more.
For consistency, the enchantment name "Void floating" should instead be "Void Floating" with a capital F.

**Comment by Nic4Las** [comment]
Your are correct. Should be fixed in the next update.
