### ISSUE TITLE
Doesn't Work with rats mod

### ISSUE THREAD

**Issue by FloppyTheWhale** [Nic4Las/Minecraft-Enderite-Mod#32]
[crash-2021-04-15_20.30.15-fml.txt](https://github.com/Nic4Las/Minecraft-Enderite-Mod/files/6321824/crash-2021-04-15_20.30.15-fml.txt)
When I downloaded the rats mod after already having the enderite mod I get an error saying:
"Rats (rats) has failed to load correctly
java.lang.ExceptionInInitializerError: null"

After doing some testing, I learned that with this problem occurs with the enderite mod installed.

Update: I am kinda new to modding but found the registry error with the bow, is there any way I can get rid of the bow?

**Comment by Pitti11** [comment]
Thank you for reporting, we finally found a major error because of the crashes with rats. We tested it in 1.16.5 and it should work know.
