### ISSUE TITLE
Disable/Enable certain items (Config)

### ISSUE THREAD

**Issue by Ohada214** [Nic4Las/Minecraft-Enderite-Mod#34]
Would be nice, if we could **turn off** every new item like:

Enderite **Crossbow**
Endeire **Bow**
Enderite **Shield**
Enderite **Shears** 
Enderite **Shulkerbox**
Enderite **Elytra**
Enderite **Elytra Chestplate**

The reason why I'm asking for this is to make this mod **feel even more vanilla friendly**. Some people might say ''If you don't like something, just don't craft it'' 

Another reason is to make these items also **unavailable** at **Roughly Enough Items** mod and **creative inventory**, if we turned them off at **Enderite mod config**, so we won't see these on the list. **Netherite Plus** mod already has such option. The point is simply not to **litter the list** with items that are not needed for some players.

**Comment by Dejeh** [comment]
Hi, I recommend you use CraftTweaker, JEI, and JEITweaker in the meantime. It's easy to disable recipes and disable viewing them in JEI.

**Comment by alexmozaidze** [comment]
Also you could use Fabrication's yeet recipes feature if you want to disable the crafting recipe. Not sure if you can hide items in REI, though

**Comment by alexmozaidze** [comment]
I requested a feature to hide recipes/items in REI and I was told that same could be achieved with KubeJS
https://github.com/shedaniel/RoughlyEnoughItems/issues/624

**Comment by Nic4Las** [comment]
Closing this as you guys seem to have figured out a workaround. If you are not happy with the solution feel free to reopen this issue.
