### ISSUE TITLE
 compatibility suggestion

### ISSUE THREAD

**Issue by Akira-Kyu** [Nic4Las/Minecraft-Enderite-Mod#35]
Hi, can you please make it possible to smelt enderite ore in furnaces from "Fabric Furnaces".(https://www.curseforge.com/minecraft/mc-mods/fabric-furnaces)

thank you very much

**Comment by Pitti11** [comment]
Well the problem is that our recipe wants a blast furnace, and the furnaces of this mod seem to be normal furnaces. So you have to find a blast furnace mod, then you can smelt our ore.
