### ISSUE TITLE
Blocks gaining NBT tag when broken

### ISSUE THREAD

**Issue by josephendren** [Nic4Las/Minecraft-Enderite-Mod#37]
If you craft a log into planks, any planks placed and picked up again won't stack with other plans in your inventory. Looks to be because breaking blocks adds some NBT to the broken blocks, only occurring since the latest update.

**Comment by Pitti11** [comment]
Oh no, this is a major bug. Thank you very much for reporting.

**Comment by Pitti11** [comment]
Fixed with commit #c94d198
