### ISSUE TITLE
mod compatibility 

### ISSUE THREAD

**Issue by XxMr1234GamerzxX** [Nic4Las/Minecraft-Enderite-Mod#38]
for some reason this mod "EarlyGame" cant use your axe, i dont think its their fault as it should just work with any tool thats a axe and does with any other mod without adding special cases for compatibility. 

it has a mechanic that when you crouch and right click the top of a log it will break it and make it into planks (this replaces the crafting recipe which means planks are not craftable)

this mod even picks up on the paxel for enderite  from AdaPaxels, the mod does have a json for compatibility and ive manually added your axe to it and it still will not work 

hopefully you can help find a fix, i will send a report their side to let that developer know just in case it is their mod being picky

**Comment by XxMr1234GamerzxX** [comment]
to fix this 

add to data > fabric > tags > items

"axes.json"
"shovels.json"
"hoes.json"

and specify them as tools in your mod

this will fix all my issues as i found more incompatibilities

**Comment by PuppetMasterZee** [comment]
Thanks!
