### ISSUE TITLE
ALL Items Not Stacking

### ISSUE THREAD

**Issue by Syrikal** [Nic4Las/Minecraft-Enderite-Mod#40]
When I update to the newest version, all new items will not stack with any pre-existing items. For instance, if I break a grass block or drop one on the ground, it will not stack with grass blocks that were in chests or my inventory before the update. I suspect this has something to do with the 'hotfix items not stacking after pickup' change.

**Comment by LifusChrustus** [comment]
I can confirm that. Even though it was supposed to be fixed after v0.8.0 it somehow slipped under your nose into 0.8.1.

**Comment by Nic4Las** [comment]
Should be fixed. If you still experience this issue feel free to reopen this issue.
