### ISSUE TITLE
Enderite elytra chestplate not works

### ISSUE THREAD

**Issue by BlackBirdTrr** [Nic4Las/Minecraft-Enderite-Mod#44]
Is mod works with origins mod

https://www.curseforge.com/minecraft/mc-mods/origins-forge

**Comment by geblinatorgr** [comment]
> Is mod works with origins mod
> 
> https://www.curseforge.com/minecraft/mc-mods/origins-forge

are you saying that this fixes the issue?

**Comment by Nic4Las** [comment]
I don't understand what the issue is here. Closing this for now. Feel free to reopen this issue.
