### ISSUE TITLE
Enderite Axe will not chop trees

### ISSUE THREAD

**Issue by PuppetMasterZee** [Nic4Las/Minecraft-Enderite-Mod#45]
MC: 1.17.1
Fabric API:  0.38.1+1.17
Version: enderitemc-enderitemod-1.2.5-1.17
Fabric Loader: 0.11.6

Enderite axe will not chop down trees.  All other tools behave as expected (except for the previously reported enderite shears).  All other axes are confirmed working.
List of mods in pack included.
[ListOfMods.txt](https://github.com/Nic4Las/Minecraft-Enderite-Mod/files/7059403/ListOfMods.txt)

**Comment by XxMr1234GamerzxX** [comment]
@PuppetMasterZee reported this in #38

**Comment by PuppetMasterZee** [comment]
resolved after following info in Issue #38
