### ISSUE TITLE
Enderite 1.17 says it requires 1.18?

### ISSUE THREAD

**Issue by DanMeadWasTaken** [Nic4Las/Minecraft-Enderite-Mod#47]
So, I tried loading up the fabric enderite mod for 1.17 but it kept pulling up a prompt saying it requires Minecraft 1.18? This was in a modpack of my own creation, if need be I can send modpack details

**Comment by Nic4Las** [comment]
I assume your are DanMeadWasTaken from Cursforge closing this because you have seemed to figured it out. If you still experience issuers  feel free to reopen this issue.
