### ISSUE TITLE
(1.3.1) Quickshulker implementation incomplete

### ISSUE THREAD

**Issue by princep444** [Nic4Las/Minecraft-Enderite-Mod#49]
Attempting to right click something into the enderite shulker box doesn't follow the intended outcome of placing it in automatically without opening it/any other action, instead swapping the box's place for said item.

Can be replicated by:
1. Picking up any item you can put in a shulker
2. Right clicking on the enderite shulker with item in hand
3. ??? Problem

**Comment by Nic4Las** [comment]
Good catch forgot to add it. Should be fixed with 1.3.2.
