### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by CreatorGamer** [Nic4Las/Minecraft-Enderite-Mod#5]
Will this mod is available for forge if so will it be in the near future or not any time soon. I know these things are hard to do but I would like to add it to my modpack and was just curious if it will be out for forge any time soon.

**Comment by Nic4Las** [comment]
We just got the forge version somewhat stable. Now we can focus on implementing the hard stuff. You can expect a beta version within the next few days. No promises on stability though. So you should probably wait a while and see how stable the mod is before adding it to your modpack.
