### ISSUE TITLE
Right click quickshulker shortcuts broken

### ISSUE THREAD

**Issue by princep444** [Nic4Las/Minecraft-Enderite-Mod#53]
When an enderite shulker box has 27 or more items/stacks, right click functions, like right clicking an item into or out of the box, stop working. If less than 27, everything works as it should.

**Comment by Nic4Las** [comment]
Good catch. Its also possible to loose items that way.  For now we will disable the bundel behavior. I will try and get in contact with the dev of  quickshulker to see if there is a way of fixing this.
The bundel behavior and the corresponding item deletion bug will disabled with version 1.3.3.

Closing this for now may reopen when i hear back from  dev of  quickshulker.
