### ISSUE TITLE
[suggestion] diamond bartering

### ISSUE THREAD

**Issue by Kiryonn** [Nic4Las/Minecraft-Enderite-Mod#57]
I feel like diamonds are as useless. So i was wondering if maybe you could introduce a new mob that we will be able to trade with the same way we do with piglins, but with diamonds. The ender version of piglins.

**Comment by Ohada214** [comment]
This idea is decent, but I think it would fit better for a new completely different mod.``

**Comment by Nic4Las** [comment]
I like the Idee. We are currently working on something else where this might fit better into. Thanks for the suggestion though :)
