### ISSUE TITLE
Stops all other shears, vanilla and modded, from working properly!

### ISSUE THREAD

**Issue by TristanKing0** [Nic4Las/Minecraft-Enderite-Mod#60]
Seriously annoying issue, can't shear grass or glow lichen, etc.

**Comment by Pitti11** [comment]
Yes, thank you for telling us, fixed in [Release - MC 1.18.1 - v1.3.4](https://www.curseforge.com/minecraft/mc-mods/enderite-mod-for-fabric/files/3669835)
