### ISSUE TITLE
Request for Nullscape compatibility

### ISSUE THREAD

**Issue by Killercrab432** [Nic4Las/Minecraft-Enderite-Mod#65]
Currently when nullscape is being used with enderite, the enderite ore only generates in the default end biomes and it only spawns low down on the y axis (not in the full height that nullscape adds) it would be fantastic if you could add compatibility for this, thanks!

**Comment by Mnky313** [comment]
I'm also having issues with it generating on the surface with nullscape installed.

**Comment by allanonmage** [comment]
Oh, is that why it's so rare?  I didn't realize they would cause problems with each other.  Lots of mods have config files for where they generate, is there such a config file?  It would probably be a json or json5 file.

I'm on 1.19.2 Fabric
