### ISSUE TITLE
Crashes instantly client side when cracked enderite is dropped

### ISSUE THREAD

**Issue by Czhekov** [Nic4Las/Minecraft-Enderite-Mod#67]
Basically the title, it also soft locks you if you're not in a position where you can instantly pickup the cracked enderite when  you join, you have to use a NBT editor to remove it and it's pretty annoying, I can supply the modlist (around 254 mods) if I'm told how to do so, (I'm not manually typing out each mod, sorry.)

Error is shown as follows:

"Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes"
I'm no programmer, but I'm guessing the packet size is too big? I'm using the "dropz" mod if that helps at all. I'm basically soft locked from joining my server right now, and if a compatibility patch could be arranged, that'd be nice.

**Comment by Czhekov** [comment]
Also if this could be fixed by a simple config edit/server setting please let me know.

**Comment by Czhekov** [comment]
Also, I would like to note I used the wrong language, it doesn't "crash" it only kicks you from the server.

**Comment by Nic4Las** [comment]
Its kind of hard to debug this without a crash log. Its entirely possible that there is an incompatibility with one of the other mods. Feel free to reopen this if its urgent.
