### ISSUE TITLE
crossbow texture glitched?

### ISSUE THREAD

**Issue by Vexxen1** [Nic4Las/Minecraft-Enderite-Mod#69]
![2022-10-22_19 55 53](https://user-images.githubusercontent.com/59104027/197371044-079c993f-6236-45b0-b852-671d599b9f17.png)
The enderite crossbow looks wooden, and its animations do not work, however it does still fire projectiles.

**Comment by Nic4Las** [comment]
Hard to say why this is happening. My guess is that it has something to do with the resource pack you are using. Closing this for now. If it is urgent feel free to reopen it.
