### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Retronixis** [Nic4Las/Minecraft-Enderite-Mod#7]
I created A server for my friends and me, though there is one problem.. Whenever I Shift + right click the sword the server immediately shuts down and closes. I think that it might be an issue for anyone trying to use it on A server

https://pastebin.com/raw/Nx5agLvY

**Comment by Pitti11** [comment]
@Retronixis thanks for the report, I found the problem. I will fix it soon. For the time being try not to use the sword while you have ender pearls in your inventory.
