### ISSUE TITLE
If you're wearing a cape of some kind, disable it while wearing an Enderite Elytra Chestplate.

### ISSUE THREAD

**Issue by MagmaBro123** [Nic4Las/Minecraft-Enderite-Mod#79]
Title. Happens with/without other mods.

![2023-04-13_23 35 45](https://user-images.githubusercontent.com/51277766/231950838-d74435db-cf35-4800-bfa6-0dd1bc5f4770.png)

**Comment by Pitti11** [comment]
Should be fixed in mod version 1.5.0+ (1.20+)
