### ISSUE TITLE
Enderite Mod v1.1.3 - Enderite Shulker Box Dyeing

### ISSUE THREAD

**Issue by rxay579** [Nic4Las/Minecraft-Enderite-Mod#8]
If you dye an Enderite shulker box in a crafting table per the usual vanilla method of dyeing shulker boxes, the output is an appropriately dyed regular shulker box and I don't think this was intended.

I don't know if you were planning to add dyed variations of the Enderite shulker boxes, but it would be nice to have them dyeable or at least not so easily converted back into a regular shulker box.

**Comment by Nic4Las** [comment]
No that is a bug thanks for the report. We will look into it.
