### ISSUE TITLE
What does the Enderite Elytra do?

### ISSUE THREAD

**Issue by allanonmage** [Nic4Las/Minecraft-Enderite-Mod#81]
I was poking around with commands and saw an elytra as part of the mod.  It's green and is called chestplate elytra separated or something like that.  Is there an advantage this had over a regular elytra?

**Comment by Pitti11** [comment]
It's a normal feature, it was just forgotten in the creative tab^^ you should be able to craft it in the smithing table. It has the same durability as the chestplate elytra, so I would say the advantage is the "no chestplate" look.

**Comment by allanonmage** [comment]
But how do you separate the chestplate and Elytra once you combine them?
