### ISSUE TITLE
Feature Request - Compatibility with ShulkerBoxTooltip

### ISSUE THREAD

**Issue by rxay579** [Nic4Las/Minecraft-Enderite-Mod#9]
It would be nice to have a preview available with the the Enderite shulker box.
https://github.com/MisterPeModder/ShulkerBoxTooltip

**Comment by Pitti11** [comment]
Yeah, I will look into that for the 1.16.2 version.

**Comment by Pitti11** [comment]
![grafik](https://user-images.githubusercontent.com/43349907/90340427-648bfa00-dff8-11ea-9f69-37bfcc90bc93.png)
Will be in the 1.16.2 update!
